### ISSUE TITLE
Absense types are not shown correctly

### ISSUE THREAD

**Issue by hakaotu** [futurice/haskell-mega-repo#274]
<img width="433" alt="screen shot 2017-03-02 at 16 16 25" src="https://cloud.githubusercontent.com/assets/7211272/23511662/938ff3f4-ff66-11e6-8b09-39fb21ce86bb.png">

**Comment by phadej** [comment]
What is the correct way?

**Comment by hakaotu** [comment]
<img width="379" alt="screen shot 2017-03-03 at 8 36 38" src="https://cloud.githubusercontent.com/assets/7211272/23540855/913f7882-ffec-11e6-9c86-8207dc05ff43.png">

I feel that those ID numbers are not needed and I'd add these absense types here so that you know which absense your are taking :)

**Comment by phadej** [comment]
I hope the names in that list are available thru API, let's see.

**Comment by phadej** [comment]
fixed
