### ISSUE TITLE
bytestring--lt-0_10_4 flag causes troubles with stack 1.5.1

### ISSUE THREAD

**Issue by kamilwaheed** [futurice/haskell-mega-repo#457]
Cloning the repo, and trying to do anything with stack spits:

```
Could not parse '/Users/kwah/futurice/haskell-mega-repo/stack.yaml':
Aeson exception:
Error in $.flags.cassava['bytestring--lt-0_10_4']: failed to parse field 'flags': Invalid flag name: "bytestring--lt-0_10_4"
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

Details: https://github.com/hvr/cassava/pull/155

Not sure if I can suggest any fixes to this since I'm fairly new to the Haskell land, but it feels like a straight-forward fix.

**Comment by phadej** [comment]
Upgrade stack to `master` version or use `cabal new-build`.

**Comment by phadej** [comment]
Also you could run into https://github.com/commercialhaskell/stack/issues/2577 which though closed, isn't entirely solved IIRC.
