### ISSUE TITLE
FUM6: password requirements

### ISSUE THREAD

**Issue by kimmoahokas** [futurice/haskell-mega-repo#516]
When changing user password (iether by generating one or letting user set one, check that the password is good enough. We don't want to impose stupid rules that result in using "p4aSSword!" as the password. Instead, encourage something like correct-horse-battery-staple and verify with following tools:

1. Estimate the password strength with https://github.com/dropbox/zxcvbn
2. Check that the password has not been used before: https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

**Comment by phadej** [comment]
Someone should port zxcvbn to Haskell ;)

**Comment by kimmoahokas** [comment]
I found two Haskell versions:

- Native but old: https://github.com/grkuntzmd/zxcvbn-Haskell
- Bindings to C version https://hackage.haskell.org/package/zxcvbn-c
