### ISSUE TITLE
Readme should point out that one has to copy the data folder on initial setup

### ISSUE THREAD

**Issue by k-nut** [futurice/haskell-mega-repo#845]
I just cloned the repo and wanted to run the `hours-mock-server`. It failed though because some of the dependencies were trying to access json config files (such as `career-levels.json`) which were not available. I realised that this data is in `data.sample` and needs to be copied to `data`. 

I'm not sure if this applies to *every* possible app one might want to run form this repo so I did not want to just add it to the README but I still that it should be somehow mentioned. Maybe someone with a better understanding of the repo structure can say if this is something that every developer will have to do, no matter what app they want to work on or if it is limited to certain apps?

**Comment by neurogoo** [comment]
Good notice. I could had sweared that there was mention of it, but I don't see it now. Maybe I was thinking of adding that, but forgot. I will add mention of it. The need for those files is case by case bases, but I think most of the apps in the repo either directly or indirectly needs those.

**Comment by neurogoo** [comment]
Added step for copying data.sample directory in README.md https://github.com/futurice/haskell-mega-repo/pull/848

**Comment by neurogoo** [comment]
Merged #848
